controller_list:
  - name: fake_rover_arm_controller
    joints:
      - base_arm_hinge
      - lower_hinge
      - upper_hinge
      - forearm_hinge
      - wrist_hinge
  - name: fake_rover_claw_controller
    joints:
      - claw_left_hinge
      - claw_right_hinge
initial:  # Define initial robot poses.
  - group: rover_arm
    pose: grab
  - group: rover_claw
    pose: closed