# Configuration Settings for NEO-M9N connected via serial port
 
debug: 1                    # Range 0-4 (0 means no debug statements will print)
 
device: /dev/ttyACMUbloxGPS
frame_id: gps_link
rate: 20.0                  # in Hz
nav_rate: 6                 # [# of measurement cycles], recommended 1 Hz
config_on_startup: true
 
raw_data: true
 
uart1:
  baudrate: 9600
 
inf:
  all: false                   # Whether to display all INF messages in console

