# Configuration Settings for NEO-M9N connected via serial port
 
debug: 1                    # Range 0-4 (0 means no debug statements will print)
 
device: /dev/ttyACM0
frame_id: neom9nraw
rate: 4                     # in Hz
nav_rate: 1                 # [# of measurement cycles], recommended 1 Hz, may
                            # be either 5 Hz (Dual constellation) or
                            # 8 Hz (GPS only)
 
config_on_startup: true
 
raw_data: true
 
uart1:
  baudrate: 9600
 
inf:
  all: false                   # Whether to display all INF messages in console
