#!/usr/bin/env python

import sys

from rqt_science.plugin import SciencePlugin
from rqt_gui.main import Main

plugin = 'rqt_science'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
