TrajectoryPlannerROS:

  acc_lim_x:  0.5
  acc_lim_y:  0.5
  acc_lim_theta: 1.00
  max_vel_x:  0.27
  min_vel_x:  0.20
  max_rotational_vel: 0.4 #was 0.550
  min_in_place_rotational_vel: 0.25 #was 0.15
  holonomic_robot: false

  xy_goal_tolerance:  0.05
  yaw_goal_tolerance: 0.05

  sim_time: 1.5
  sim_granularity: 0.025
  vx_samples: 12
  vtheta_samples: 20

  # goal_distance_bias: 0.8
  # path_distance_bias: 0.6
  # occdist_scale: 0.01
  # heading_lookahead: 0.325
  # dwa: true

  # oscillation_reset_dist: 0.05
  # meter_scoring: true


  # # meter_scoring: true


  # pdist_scale: 1.0 # The higher will follow more the global path.
  # gdist_scale: 0.8
  # occdist_scale: 0.01
  # publish_cost_grid_pc: false

  goal_distance_bias: 0.8
  path_distance_bias: 0.6
  occdist_scale: 0.01
  heading_lookahead: 0.325
  dwa: true

  oscillation_reset_dist: 0.05
  meter_scoring: true

NavfnROS:
  allow_unknown: true
  visualize_potential: false