#global_costmap
global_frame: map
robot_base_frame: chassis
update_frequency: 1
publish_frequency: 1
static_map: true
always_send_full_costmap: true
width: 100
height: 100
resolution: 0.05
origin_x: -50.0
origin_y: -50.0
# inflation_radius: 0.01

plugins:
  - {name: static_layer, type: "rtabmap_ros::StaticLayer"}
  - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: inflation, type: "costmap_2d::InflationLayer"}

# global_frame: map
# robot_base_frame: chassis
# update_frequency: 1
# publish_frequency: 1  
# always_send_full_costmap: false
# static_map: true
# plugins:
#    - {name: static_layer, type: "rtabmap_ros::StaticLayer"}
#    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
#    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}